const Lumi=(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],get=(k,d)=>{try{return JSON.parse(localStorage.getItem('lumi_'+k))??d}catch{return d}},set=(k,v)=>localStorage.setItem('lumi_'+k,JSON.stringify(v));let cfg=get('cfg',{name:'',accent:'#7fe3ff',memory:true,voiceReplies:true,notify:true,alwaysListen:false}),tasks=get('tasks',[]),events=get('events',[]),chat=get('chat',[]),month=0,day=null;if(!cfg||typeof cfg!=='object')cfg={name:'',accent:'#7fe3ff',memory:true,voiceReplies:false,notify:true};cfg={name:typeof cfg.name==='string'?cfg.name:'',accent:typeof cfg.accent==='string'?cfg.accent:'#7fe3ff',memory:cfg.memory!==false,voiceReplies:cfg.voiceReplies===true,notify:cfg.notify!==false,alwaysListen:cfg.alwaysListen===true};if(!Array.isArray(tasks))tasks=[];if(!Array.isArray(events))events=[];if(!Array.isArray(chat))chat=[];
const now=()=>new Date(),hm=()=>now().toTimeString().slice(0,5),name=()=>cfg.name||'Mau',pad=n=>String(n).padStart(2,'0');
function apply(){document.documentElement.style.setProperty('--accent',cfg.accent);if($('#homeName'))$('#homeName').textContent=name();if($('#setName'))$('#setName').value=cfg.name||'';$$('.sw').forEach(x=>x.classList.toggle('on',!!cfg[x.dataset.k]))}
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));const e=$('#'+id);if(e)e.classList.add('active');$$('.navbar button').forEach(b=>b.classList.toggle('active',b.dataset.s===id));if(id==='s-chat')renderChat(true);if(id==='s-tasks')renderTasks();if(id==='s-cal')renderCal();if(id==='s-media')renderPlaylist();if(id==='s-well')renderMood()}
const AI_ENDPOINT=(localStorage.getItem('lumi_ai_endpoint')||'https://education-bloque4-test-production.up.railway.app/chat').trim();
let aiBusy=false;
function aiHistory(){return chat.slice(-12).map(m=>({role:m.who==='user'?'user':'assistant',content:String(m.text||'')}))}
async function askAI(text){
  if(!AI_ENDPOINT||aiBusy)return null;
  aiBusy=true;
  try{
    const r=await fetch(AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:aiHistory(),user:{name:cfg.name||'',locale:navigator.language||'es-ES'}})});
    if(!r.ok)throw new Error('HTTP '+r.status);
    const d=await r.json();
    const answer=typeof d.reply==='string'?d.reply:(typeof d.content==='string'?d.content:'');
    return answer.trim()||null;
  }catch(e){console.warn('Lumi AI backend:',e);return null}
  finally{aiBusy=false}
}
const EXTERNAL_APPS={WhatsApp:'https://wa.me/',YouTube:'https://www.youtube.com/',Correo:'https://mail.google.com/',Navegador:'https://www.google.com/',Instagram:'https://www.instagram.com/',TikTok:'https://www.tiktok.com/',Facebook:'https://www.facebook.com/',Gmail:'https://mail.google.com/',Telegram:'https://t.me/',Spotify:'https://open.spotify.com/',Netflix:'https://www.netflix.com/',Maps:'https://maps.google.com/', 'Play Store':'https://play.google.com/store',Drive:'https://drive.google.com/',Noticias:'https://news.google.com/'};function openExternal(label){const url=EXTERNAL_APPS[label];if(!url){toast('No tengo configurado '+label);return}if(window.AndroidLumi&&typeof window.AndroidLumi.openExternal==='function'){window.AndroidLumi.openExternal(url);return}const w=window.open(url,'_blank');if(!w)location.href=url}function grid(id,items){const e=$(id);if(!e)return;e.innerHTML='';items.forEach(([ic,l])=>{const d=document.createElement('div');d.className='card';d.innerHTML='<div class="ci">'+ic+'</div><p>'+l+'</p>';d.onclick=()=>{const m={Apps:'s-apps',Multimedia:'s-media',Calendario:'s-cal',Tareas:'s-tasks',Recordatorios:'s-tasks',Ajustes:'s-set'};m[l]?go(m[l]):openExternal(l)};e.appendChild(d)})}
const ACTIONS=[['💬','WhatsApp'],['▶️','YouTube'],['✉️','Correo'],['🌐','Navegador'],['📱','Apps'],['🎵','Multimedia'],['📅','Calendario'],['⏰','Recordatorios'],['✅','Tareas'],['⚙️','Ajustes']],APPS=[['💬','WhatsApp'],['📸','Instagram'],['🎵','TikTok'],['👥','Facebook'],['✉️','Gmail'],['✈️','Telegram'],['🎧','Spotify'],['🎬','Netflix'],['🗺️','Maps'],['🛒','Play Store'],['📁','Drive'],['📖','Noticias']];
function brain(t){const x=t.toLowerCase().trim();if(/\b(sub(e|a)|baja|disminuye|reduce)\s+(el\s+)?volumen\b/.test(x)){if(window.AndroidLumi?.volumeDown)window.AndroidLumi.volumeDown();return'Bajando el volumen.'}if(/\b(sub(e|a)|aumenta)\s+(el\s+)?volumen\b/.test(x)){if(window.AndroidLumi?.volumeUp)window.AndroidLumi.volumeUp();return'Subiendo el volumen.'}if(/\b(cambia|siguiente|pr[oó]xima)\s+(canci[oó]n|tema|m[uú]sica)\b/.test(x)){if(window.AndroidLumi?.mediaNext)window.AndroidLumi.mediaNext();return'Voy con la siguiente canción.'}if(/\b(anterior|regresa|retrocede)\s+(canci[oó]n|tema)\b/.test(x)){if(window.AndroidLumi?.mediaPrevious)window.AndroidLumi.mediaPrevious();return'Voy a la canción anterior.'}if(/\b(pausa|pausar|det[eé]n|detener)\b/.test(x)&&/m[uú]sica|canci[oó]n|video|youtube/.test(x)){if(window.AndroidLumi?.mediaPlayPause)window.AndroidLumi.mediaPlayPause();return'Pausando la reproducción.'}let m=x.match(/(?:agrega|añade|crea)\s+(?:una\s+)?tarea[:\s]+(.+)/);if(m){addTaskFrom(m[1]);return'Hecho. Agregué la tarea: '+m[1]+'.'}m=x.match(/(?:recuerda|recu[eé]rdame|ponme\s+un\s+recordatorio)\s+(.+)/);if(m){const text=m[1];addTaskFrom('Recordar: '+text);const tm=text.match(/mañana.*?(\d{1,2})(?::(\d{2}))?\s*(?:de la\s+)?(mañana|tarde|noche)?/i);if(tm){const d=new Date(now());d.setDate(d.getDate()+1);let h=Number(tm[1]);const min=Number(tm[2]||0);const ap=(tm[3]||'').toLowerCase();if(ap==='tarde'&&h<12)h+=12;if(ap==='noche'&&h<12)h+=12;const k=d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());events.push({d:k,time:pad(h)+':'+pad(min),text:'Recordatorio: '+text});set('events',events);renderCal()}return'Sí. Te lo dejé como recordatorio: '+text+'.'}if(x.includes('hora'))return'Son las '+hm()+'.';if(x.includes('fecha')||x.includes('qué día'))return'Hoy es '+now().toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long',year:'numeric'})+'.';if(x.includes('tarea')||x.includes('pendiente'))return tasks.filter(t=>!t.done).length+' tarea(s) pendiente(s).';if(x.includes('bienestar')||x.includes('medita')){setTimeout(()=>go('s-well'),300);return'Vamos a Bienestar. Estoy contigo. 🌿'}if(x.includes('música')||x.includes('musica')){setTimeout(()=>go('s-media'),300);return'Vamos a música. 🎵'}if(x.includes('quién eres')||x.includes('quien eres'))return'Soy Lumi. Tu asistente virtual total y tu compañera de confianza: puedo ayudarte a pensar, organizarte, escucharte y acompañarte.';if(x.includes('hola'))return'Hola, '+name()+'. Aquí estoy contigo. ¿Qué necesitas?';if(x.includes('gracias'))return'Siempre. 💜';return'Entiendo. Déjame pensarlo y ayudarte con eso.'}
function push(w,t){chat.push({who:w,text:t,t:hm()});if(cfg.memory)set('chat',chat)}
function renderChat(scroll){const b=$('#chatbox');if(!b)return;b.innerHTML='';if(!chat.length)push('lumi','¡Hola '+name()+'! ✨ Soy Lumi. ¿En qué te ayudo hoy?');chat.forEach(m=>{const d=document.createElement('div');d.className='msg '+m.who;d.innerHTML=m.text.replace(/</g,'&lt;').replace(/\n/g,'<br>')+'<span class="t">'+m.t+'</span>';b.appendChild(d)});if(scroll)b.scrollTop=b.scrollHeight}
async function send(){const i=$('#chatIn'),t=i&&i.value.trim();if(!t||aiBusy)return;push('user',t);i.value='';renderChat(true);if(window.__lumiEducation?.lumiMediaCommand&&window.__lumiEducation.lumiMediaCommand(t)){push('lumi','Entendido. Estoy abriendo el contenido que pediste.');renderChat(true);if(cfg.alwaysListen)setTimeout(alwaysListen,900);return}const remote=await askAI(t);const r=remote||brain(t);push('lumi',r);renderChat(true);if(cfg.voiceReplies)speak(r);else if(cfg.alwaysListen)setTimeout(alwaysListen,350)}
function clearChat(){chat=[];set('chat',chat);renderChat(true);toast('Conversación limpiada ✨')}
let rec=null,alwaysRec=null;function toggleVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('El reconocimiento de voz no está disponible en este Android');return}if(rec){try{rec.stop()}catch{};rec=null;return}try{rec=new R();}catch(e){rec=null;toast('No se pudo iniciar la voz');return}rec.lang='es-ES';rec.continuous=false;rec.interimResults=false;rec.maxAlternatives=1;rec.onstart=()=>$('#voiceState').textContent='Escuchando…';rec.onresult=e=>{const text=(e.results?.[0]?.[0]?.transcript||'').trim();$('#voiceText').textContent=text;if(text){$('#chatIn').value=text;go('s-chat');send()}};rec.onerror=e=>{if(e?.error!=='aborted')toast('La voz no pudo iniciarse: '+(e&&e.error?e.error:'error'));};rec.onend=()=>{rec=null;$('#voiceState').textContent='Toca el orbe para hablar'};try{rec.start()}catch(e){rec=null;$('#voiceState').textContent='Toca el orbe para hablar';toast('El micrófono fue bloqueado')}}
function startDictation(){go('s-voice');setTimeout(toggleVoice,300)}
function alwaysListen(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('Este Android no permite escucha continua desde el WebView');return false}if(alwaysRec)return true;cfg.alwaysListen=true;set('cfg',cfg);const listen=()=>{if(!cfg.alwaysListen||alwaysRec)return;try{alwaysRec=new R();}catch{return}const r=alwaysRec;r.lang='es-ES';r.continuous=false;r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>{const e=$('#voiceState');if(e)e.textContent='Lumi está escuchando…'};r.onresult=e=>{const text=(e.results?.[0]?.[0]?.transcript||'').trim();if(text){const i=$('#chatIn');if(i)i.value=text;send()}};r.onerror=()=>{if(alwaysRec===r)alwaysRec=null;if(cfg.alwaysListen)setTimeout(listen,700)};r.onend=()=>{if(alwaysRec===r)alwaysRec=null;if(cfg.alwaysListen&&!window.__lumiNativeSpeaking&&!aiBusy)setTimeout(listen,350)};try{r.start()}catch{alwaysRec=null;if(cfg.alwaysListen)setTimeout(listen,700)}};listen();toast('Lumi queda escuchando mientras la app está abierta.');return true}
function stopAlwaysListen(){cfg.alwaysListen=false;set('cfg',cfg);try{alwaysRec?.stop()}catch{}alwaysRec=null;toast('Lumi dejó de escuchar.')}function toggleAlwaysListen(){if(cfg.alwaysListen)stopAlwaysListen();else alwaysListen()}function speak(t){t=String(t||'').trim();if(!t)return;window.__lumiNativeSpeaking=true;if(window.AndroidLumi&&typeof window.AndroidLumi.speak==='function'){window.AndroidLumi.speak(t);return}if(!('speechSynthesis'in window)){window.__lumiNativeSpeaking=false;return}const u=new SpeechSynthesisUtterance(t);u.lang='es-ES';u.onend=()=>{window.__lumiNativeSpeaking=false};u.onerror=()=>{window.__lumiNativeSpeaking=false};speechSynthesis.cancel();speechSynthesis.speak(u)}
window.__lumiNativeSpeechDone=()=>{window.__lumiNativeSpeaking=false;if(cfg.alwaysListen&&!alwaysRec&&!aiBusy)setTimeout(alwaysListen,350)};
function stopSpeaking(){window.__lumiNativeSpeaking=false;if(window.AndroidLumi&&typeof window.AndroidLumi.stopSpeaking==='function'){window.AndroidLumi.stopSpeaking();return}if('speechSynthesis'in window)speechSynthesis.cancel()}function speakTest(){speak('Hola '+name()+'. Soy Lumi, tu asistente virtual total. Esta es una prueba de la voz seleccionada.')}function selectVoice(){if(window.__lumiEducation?.chooseLumiVoice){window.__lumiEducation.chooseLumiVoice();return}if(window.AndroidLumi?.getVoices){const raw=window.AndroidLumi.getVoices();try{const list=JSON.parse(raw);const options=list.map((v,i)=>(i+1)+'. '+v.name+' — '+v.locale).join('\\n');const pick=prompt('Voces disponibles:\\n\\n'+options+'\\n\\nEscribe el número:','1');if(pick===null)return;const v=list[Number(pick)-1];if(v&&window.AndroidLumi.setVoice(v.name)){localStorage.setItem('lumi_android_voice',v.name);speak('Hola, soy Lumi. Esta es la voz que elegiste.')}}catch{}}}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function renderTasks(){const e=$('#taskList');if(!e)return;e.innerHTML=tasks.length?'':'<p class="sub">Sin tareas. ¡Todo bajo control! 🎉</p>';tasks.forEach((t,i)=>{if(!t||typeof t!=='object')return;const text=esc(t.text??'');e.insertAdjacentHTML('beforeend','<div class="task'+(t.done?' done':'')+'"><div class="ck" onclick="Lumi.checkTask('+i+')">✔</div><span>'+text+'</span><button class="del" onclick="Lumi.delTask('+i+')">✕</button></div>')})}
function addTask(){const i=$('#taskIn');if(!i.value.trim())return;addTaskFrom(i.value.trim());i.value='';toast('Tarea agregada ✅')}function addTaskFrom(t){t=String(t??'').trim();if(!t)return;tasks.push({text:t,done:false});set('tasks',tasks);renderTasks()}function checkTask(i){tasks[i].done=!tasks[i].done;set('tasks',tasks);renderTasks()}function delTask(i){tasks.splice(i,1);set('tasks',tasks);renderTasks()}
const MONTHS=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];function shiftMonth(n){month+=n;renderCal()}function renderCal(){const b=new Date(now().getFullYear(),now().getMonth()+month,1),y=b.getFullYear(),mo=b.getMonth(),g=$('#calGrid');if(!g)return;$('#calTitle').textContent=MONTHS[mo]+' '+y;g.innerHTML=['L','M','M','J','V','S','D'].map(x=>'<div class="hd">'+x+'</div>').join('');const first=(new Date(y,mo,1).getDay()+6)%7,days=new Date(y,mo+1,0).getDate();for(let i=0;i<first;i++)g.insertAdjacentHTML('beforeend','<div class="d"></div>');for(let d=1;d<=days;d++){const k=y+'-'+pad(mo+1)+'-'+pad(d),e=document.createElement('div');e.className='d'+(k===now().getFullYear()+'-'+pad(now().getMonth()+1)+'-'+pad(now().getDate())&&month===0?' today':'')+(events.some(v=>v.d===k)?' has':'')+(day===k?' sel':'');e.textContent=d;e.onclick=()=>{day=day===k?null:k;renderCal()};g.appendChild(e)}const l=$('#eventList');l.innerHTML='';const list=day?events.map((e,i)=>({e,i})).filter(x=>x.e.d===day):events.map((e,i)=>({e,i})).filter(x=>x.e.d.startsWith(y+'-'+pad(mo+1)));list.forEach(x=>l.insertAdjacentHTML('beforeend','<div class="event"><button class="del" onclick="Lumi.delEvent('+x.i+')">✕</button><b>'+esc(x.e.time)+'</b> · '+esc(x.e.text)+'</div>'));if(!list.length)l.insertAdjacentHTML('beforeend','<p class="sub">Sin eventos. ¡Agenda algo bonito! 📅</p>')}
function addEvent(){const i=$('#eventIn'),v=i.value.trim(),m=v.match(/(\d{1,2})\s+(\d{1,2}:\d{2}|todo el día)\s+(.+)/i)||v.match(/(\d{1,2})\s+(.+)/);if(!m){toast('Formato: 15 18:00 Gimnasio');return}const base=new Date(now().getFullYear(),now().getMonth()+month,1),dayNum=Number(m[1]),maxDay=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();if(dayNum<1||dayNum>maxDay){toast('Ese día no existe en el mes seleccionado');return}events.push({d:base.getFullYear()+'-'+pad(base.getMonth()+1)+'-'+pad(dayNum),time:m.length===4?m[2]:'todo el día',text:m.length===4?m[3]:m[2]});set('events',events);i.value='';renderCal();toast('Evento agendado 📅')}function delEvent(i){events.splice(i,1);set('events',events);renderCal()}
const TRACKS=[['🎵','Música para concentrarte','Focus · 24 min'],['🌙','Música relajante para dormir','Ambient · 42 min'],['🌲','Lo mejor de la naturaleza','Sonidos · 31 min'],['✨','Chulas motivacionales','Playlist · 18 min']];let cur=0,playing=false,prog=0,timer;function renderPlaylist(){if(!$('#playlist'))return;$('#playerTitle').textContent=TRACKS[cur][1];$('#playerArt').textContent=TRACKS[cur][0];$('#playlist').innerHTML=TRACKS.map((t,i)=>'<div class="track'+(i===cur?' playing':'')+'"><span>'+t[0]+'</span><div class="ti">'+t[1]+'<small>'+t[2]+'</small></div><span>▶️</span></div>').join('');$$('.track').forEach((e,i)=>e.onclick=()=>{cur=i;prog=0;renderPlaylist()})}function togglePlay(){playing=!playing;$('#playBtn').textContent=playing?'⏸️':'▶️';clearInterval(timer);if(playing)timer=setInterval(()=>{prog=Math.min(100,prog+1);$('#pbar').style.width=prog+'%';if(prog>=100)nextTrack()},1000)}function nextTrack(){cur=(cur+1)%TRACKS.length;prog=0;renderPlaylist()}function prevTrack(){cur=(cur-1+TRACKS.length)%TRACKS.length;prog=0;renderPlaylist()}
let breathing=false,bTimer;function toggleBreath(){breathing=!breathing;$('#breathBtn').textContent=breathing?'Detener':'Comenzar respiración guiada';clearTimeout(bTimer);if(!breathing){$('#breathCircle').classList.remove('in');return}const c=()=>{if(!breathing)return;$('#breathCircle').classList.add('in');$('#breathLabel').textContent='Inhala…';bTimer=setTimeout(()=>{$('#breathCircle').classList.remove('in');$('#breathLabel').textContent='Exhala…';bTimer=setTimeout(c,4000)},4000)};c()}
function mood(m){set('mood',{m,t:now().toLocaleDateString('es-ES')});renderMood();toast('Registré tu ánimo '+m+' 💜')}function renderMood(){const m=get('mood',null);if($('#moodLog'))$('#moodLog').textContent=m?'Último registro: '+m.m+' · '+m.t:'Aún no registras tu ánimo hoy.'}function wellMsg(k){const m={'Escucha activa':'Te escucho sin juzgar, '+name()+'. Cuéntame lo que necesites.','Consejos personalizados':'Divide tus metas en pasos pequeños. Cada paso cuenta.','Motivación diaria':'El éxito es la suma de pequeños esfuerzos repetidos cada día.'};toast(m[k]||'Estoy aquí para ti 💜');speak(m[k]||'')}
function saveName(){const v=$('#nameInput').value.trim();if(!v)return toast('Escribe tu nombre para comenzar ✦');cfg.name=v;set('cfg',cfg);$('#onboarding').classList.add('hidden');apply();go('s-home');setTimeout(()=>speak('Hola '+v+'. Soy Lumi.'),300)}function rename(v){if(v.trim()){cfg.name=v.trim();set('cfg',cfg);apply()}}function accent(c){cfg.accent=c;set('cfg',cfg);apply()}function toggle(sw){cfg[sw.dataset.k]=!cfg[sw.dataset.k];set('cfg',cfg);apply();if(sw.dataset.k==='alwaysListen'){if(cfg.alwaysListen)alwaysListen();else stopAlwaysListen()}}function wipe(){if(confirm('¿Borrar todos los datos de Lumi?')){localStorage.clear();location.reload()}}
function openEducationCall(){if(window.__lumiEducation?.openLumiCall)window.__lumiEducation.openLumiCall();else toast('El núcleo de voz de Lumi todavía está cargando.')}function openEducationVoice(){if(window.__lumiEducation?.startVoice)window.__lumiEducation.startVoice();else startDictation()}function init(){try{const tick=()=>{const c=$('#clock');if(c)c.textContent=hm()};tick();setInterval(tick,15000);apply();if(!cfg.name)$('#onboarding').classList.remove('hidden');grid('#actionsGrid',ACTIONS);grid('#appsGrid',APPS);renderChat(false);if(cfg.alwaysListen)setTimeout(alwaysListen,900);renderTasks();renderCal();renderPlaylist();renderMood();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){console.error('Lumi init error',e);toast('Lumi tuvo un problema al iniciar. Recarga la app.')}}document.addEventListener('DOMContentLoaded',init);const API={go,send,clearChat,toggleVoice,startDictation,speakTest,stopSpeaking,selectVoice,alwaysListen,stopAlwaysListen,toggleAlwaysListen,togglePlay,nextTrack,prevTrack,toggleBreath,mood,wellMsg,addTask,addTaskFrom,checkTask,delTask,shiftMonth,addEvent,delEvent,saveName,rename,accent,toggle,wipe,openExternal,openEducationCall,openEducationVoice};window.Lumi=API;return API})()